// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review.Models;

namespace Review.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Review.Models.Reviews", b =>
                {
                    b.Property<int>("ReviewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AchievementsOnGoalsLastYear_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AchievementsOnGoalsLastYear_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalComments_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalComments_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreasImprovement_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreasImprovement_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommitmentObjectives_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommitmentObjectives_EmployeeRating")
                        .HasColumnType("int");

                    b.Property<string>("CommitmentObjectives_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommitmentObjectives_ReviewerRating")
                        .HasColumnType("int");

                    b.Property<string>("Communication_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Communication_EmployeeRating")
                        .HasColumnType("int");

                    b.Property<string>("Communication_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Communication_ReviewerRating")
                        .HasColumnType("int");

                    b.Property<bool>("ConsiderForPromotion")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeStrengths_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeStrengths_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternationalLeadership_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternationalLeadership_EmployeeRating")
                        .HasColumnType("int");

                    b.Property<string>("InternationalLeadership_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternationalLeadership_ReviewerRating")
                        .HasColumnType("int");

                    b.Property<string>("JIRAReportLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationalProcedures_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationalProcedures_EmployeeRating")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationalProcedures_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationalProcedures_ReviewerRating")
                        .HasColumnType("int");

                    b.Property<string>("Promotion_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Promotion_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SecretKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Technical_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Technical_EmployeeRating")
                        .HasColumnType("int");

                    b.Property<string>("Technical_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Technical_ReviewerRating")
                        .HasColumnType("int");

                    b.Property<string>("ThisYearGoals_EmployeeExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThisYearGoals_ReviewerExplanation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewsId");

                    b.ToTable("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
